#!/bin/sh

NAME="$1"
TYPE="$2"

if [ "$NAME" == "" ] ; then
    echo "Usage: $0 <name> [vpsadmind | api]"
    exit 1
fi

TASK="$(date +%Y-%m-%d)-$1"

mkdir "$TASK"

if [ "$TYPE" != "" ] ; then
    TPL=""

    case "$TYPE" in
        api|vpsadmin-api)
            TPL="vpsadmin-api.rb"
            ;;

        d|daemon|nodectld)
            TPL="nodectld.rb"
            ;;

        vpsadmind)
            TPL="vpsadmind.rb"
            ;;

        *)
            echo "Unknown template '$TYPE'"
            exit 1
            ;;
    esac

    cp -p templates/"$TPL" "$TASK"/"${NAME//-/_}".${TPL##*.}
fi
